### ISSUE TITLE
MariaDB 11.4 is throwing error (as replica) when replicating from Mysql master 8.0.36

### ISSUE THREAD

**Issue by saisreenivasb** [lando/mariadb#74]
Hi Team,

We are getting this error when we tried to replicate the data from Mysql master with 8.0.36 to MariaDB 11.4 (as a slave). PFB error 

Kindly let us know what would be the fix for this.

                Last_SQL_Errno: 22
                Last_SQL_Error: Error 'Character set '#255' is not a compiled character set and is not specified in the '/usr/share/mysql/charsets/Index.xml' file' on query. Default database: 'testsreeni'. Query: 'create database testsreeni'

**Comment by reynoldsalec** [comment]
@saisreenivasb haven't personally seen this issue, but from a quick Google looks like it typically happens if a character set isn't available on the "receiving" (in this case, the Lando) database; sounds like this is pretty common, since MySQL 8 has many character sets not present or not supported by MySQL 11.4.

This is an underlying issue with trying to replicate from MySQL 8.0.36 to MariaDB 11.4, not an issue with Lando itself. I shamelessly queried ChatGPT and it had the following suggestions on how to address the issue:


#### **Option 1: Adjust the Character Set on the Master**
Ensure the database and tables on the MySQL master use a character set supported by MariaDB (e.g., `utf8mb4` or `latin1`).

1. Check the default character set on the master:
   ```sql
   SHOW VARIABLES LIKE 'character_set_server';
   SHOW VARIABLES LIKE 'collation_server';
   ```

2. Update the default character set (if necessary):
   ```sql
   SET GLOBAL character_set_server = 'utf8mb4';
   SET GLOBAL collation_server = 'utf8mb4_general_ci';
   ```

3. Ensure existing databases and tables use compatible character sets:
   ```sql
   ALTER DATABASE testsreeni CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
   ALTER TABLE table_name CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
   ```

4. Restart replication.

#### **Option 2: Use MariaDB-Compatible Binlog Formats**
Ensure MySQL writes the binlog in a MariaDB-compatible format.

1. Set the `binlog_row_metadata` variable to minimal on the MySQL master:
   ```sql
   SET GLOBAL binlog_row_metadata = 'MINIMAL';
   ```

2. Check and use the `STATEMENT` or `MIXED` binlog format instead of `ROW`:
   ```sql
   SET GLOBAL binlog_format = 'STATEMENT';
   ```

3. Restart MySQL and restart replication.

---

#### **Option 3: Modify MariaDB's Character Set Files**
You can try adding the missing character set to MariaDB if you're confident it matches a MySQL-supported character set.

1. Locate MariaDB's `Index.xml` file:
   - Usually found at `/usr/share/mysql/charsets/Index.xml`.

2. Add an entry for `#255` (if appropriate). This requires knowledge of the actual character set MySQL is using.

3. Restart MariaDB.

---

#### **Option 4: Dump and Import Data**
If replication issues persist, consider using a dump-based migration instead of replication.

1. Dump the database from MySQL using a compatible character set:
   ```bash
   mysqldump --default-character-set=utf8mb4 --databases testsreeni > testsreeni.sql
   ```

2. Import the dump into MariaDB:
   ```bash
   mysql -u username -p testsreeni < testsreeni.sql
   ```

**Comment by saisreenivasb** [comment]
Can you pls let us know what exactly we need to add in mariadb index.xml file for below shared option 

Option 3: Modify MariaDB's Character Set Files
You can try adding the missing character set to MariaDB if you're confident it matches a MySQL-supported character set.

Locate MariaDB's Index.xml file:

Usually found at /usr/share/mysql/charsets/Index.xml.
Add an entry for #255 (if appropriate). This requires knowledge of the actual character set MySQL is using.

**Comment by saisreenivasb** [comment]
BI have made all the required changes earlier as well. But still not sure what exactly needs to be added in the MariaDB index.xml file and between which lines we need to add. Can you just help me on this part.

**Comment by saisreenivasb** [comment]
Im using the common character set on both Mysql & MariaDB which is utf8mb4_general_ci but still im getting same error.

Would appreciate if you could help me with the data that i need to append on the index.xml file on mariaDB instance.

**Comment by saisreenivasb** [comment]
Kindly help me on this

**Comment by AaronFeledy** [comment]
This issue appears to be related to MySQL/MariaDB replication compatibility rather than a Lando-specific problem. Mixing MySQL and MariaDB in replication setups (especially newer versions) often leads to compatibility issues like this character set error.

I'd recommend:
1. Raising this in MySQL/MariaDB support channels where you'll get more specialized help
2. Or if you specifically need heterogeneous replication in your Lando setup, please clarify why so we can better understand your use case

**Comment by saisreenivasb** [comment]
Hi Aaron,

Use Case:
We are planning to migrate our Mysql instances to MariaDB where we dont want to directly migrate at one shot instead we wanted to create one MariaDB replica under Mysql mater and then we wanted to do cutover by promoting the MariaDB slave to Master.

So is there any possibility that we can setup this without any issues with the help of any specialized tools or any other approach. Pls help us on this
